# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
cache: packages

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi

script:
  - travis_wait 30 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'; fi
